import 'package:vector_math/vector_math.dart';

/// Represents the deserialized anatomy encoding schema generated by Blender.
class AnatomySchema {
  /// Creates a new [AnatomySchema].
  const AnatomySchema({
    required this.version,
    required this.heartCenter,
    required this.layers,
  });

  /// Deserializes an [AnatomySchema] from a JSON map.
  factory AnatomySchema.fromJson(Map<String, dynamic> json) {
    final heart = json['heart_center'] as List<dynamic>;
    return AnatomySchema(
      version: json['version'] as String,
      heartCenter: Vector3(
        (heart[0] as num).toDouble(),
        (heart[1] as num).toDouble(),
        (heart[2] as num).toDouble(),
      ),
      layers: (json['layers'] as Map<String, dynamic>).map(
        (key, dynamic value) => MapEntry(
          key,
          AnatomyLayerSchema.fromJson(value as Map<String, dynamic>),
        ),
      ),
    );
  }

  /// The schema version.
  final String version;

  /// The global position of the heart.
  final Vector3 heartCenter;

  /// A map of anatomical layers.
  final Map<String, AnatomyLayerSchema> layers;
}

/// Represents a single anatomical layer in the schema.
class AnatomyLayerSchema {
  /// Creates a new [AnatomyLayerSchema].
  const AnatomyLayerSchema({
    required this.meshes,
    required this.proceduralTypes,
  });

  /// Deserializes an [AnatomyLayerSchema] from a JSON map.
  factory AnatomyLayerSchema.fromJson(Map<String, dynamic> json) {
    return AnatomyLayerSchema(
      meshes: (json['meshes'] as Map<String, dynamic>).map(
        (key, dynamic value) => MapEntry(
          key,
          AnatomyMeshSchema.fromJson(value as Map<String, dynamic>),
        ),
      ),
      proceduralTypes: (json['procedural_types'] as Map<String, dynamic>).map(
        (key, dynamic value) => MapEntry(key, List<String>.from(value as List)),
      ),
    );
  }

  /// A map of all meshes in the layer.
  final Map<String, AnatomyMeshSchema> meshes;

  /// A map associating procedural types with mesh names.
  final Map<String, List<String>> proceduralTypes;
}

/// Represents a single mesh in the schema.
class AnatomyMeshSchema {
  /// Creates a new [AnatomyMeshSchema].
  const AnatomyMeshSchema({
    required this.proceduralType,
    required this.vertexCount,
    required this.faceCount,
    required this.origin,
    required this.boundingCenter,
  });

  /// Deserializes an [AnatomyMeshSchema] from a JSON map.
  factory AnatomyMeshSchema.fromJson(Map<String, dynamic> json) {
    final orig = json['origin'] as List<dynamic>;
    final center = json['bounding_center'] as List<dynamic>;
    return AnatomyMeshSchema(
      proceduralType: json['procedural_type'] as String,
      vertexCount: json['vertex_count'] as int,
      faceCount: json['face_count'] as int,
      origin: Vector3(
        (orig[0] as num).toDouble(),
        (orig[1] as num).toDouble(),
        (orig[2] as num).toDouble(),
      ),
      boundingCenter: Vector3(
        (center[0] as num).toDouble(),
        (center[1] as num).toDouble(),
        (center[2] as num).toDouble(),
      ),
    );
  }

  /// The procedural type assigned to the mesh.
  final String proceduralType;

  /// The number of vertices.
  final int vertexCount;

  /// The number of faces.
  final int faceCount;

  /// The origin point of the mesh.
  final Vector3 origin;

  /// The bounding center of the mesh.
  final Vector3 boundingCenter;
}
