name: myotwin_ui
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

resolution: workspace

environment:
  sdk: ">=3.11.5"
  flutter: ">=3.41.9"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
