name: motus_hub
description: MOTUS Hub server for Ollama client, tool calling, RAG, background schedule.
version: 0.0.1
publish_to: none

resolution: workspace

environment:
  sdk: '>=3.11.5'

dependencies:
  drift: ^2.0.0
  fpdart: ^1.2.0
  shared_core:
    path: ../shared_core
  shelf: ^1.4.0
  shelf_router: ^1.1.4

dev_dependencies:
  test: ^1.25.0
